/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloBeans.BeansSecretario;
import ModeloBeans.ModeloTabela;
import ModeloConeciton.ConexaoBanco;
import ModeloDao.DaoSecretario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Victor
 */
public class TelaSecretario extends javax.swing.JFrame {

    BeansSecretario Mod = new BeansSecretario();
    DaoSecretario Dao = new DaoSecretario();
    ConexaoBanco Conex = new ConexaoBanco(); 
    int flag = 0; 
    public TelaSecretario() {
        initComponents();
        PreencherTabela("select * from secretario order by Nomesecre");//CHAMA A TABELA LOGO AO ABRIR
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CPFSecretario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        NumeroSecretario = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TelaSecretario = new javax.swing.JTable();
        EnviarSecretario = new javax.swing.JButton();
        EditarSecretario = new javax.swing.JButton();
        CancelarSecretario = new javax.swing.JButton();
        ExcluirSecretario = new javax.swing.JButton();
        NomeSecretario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IDSecretario = new javax.swing.JTextField();
        NovoSecretario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Nome : ");

        jLabel4.setText("Numero :");

        try {
            CPFSecretario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFSecretario.setEnabled(false);

        jLabel3.setText("CPF : ");

        try {
            NumeroSecretario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        NumeroSecretario.setEnabled(false);

        TelaSecretario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TelaSecretario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelaSecretarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TelaSecretario);

        EnviarSecretario.setText("Enviar");
        EnviarSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarSecretarioActionPerformed(evt);
            }
        });

        EditarSecretario.setText("Editar");
        EditarSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarSecretarioActionPerformed(evt);
            }
        });

        CancelarSecretario.setText("Cancelar");
        CancelarSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarSecretarioActionPerformed(evt);
            }
        });

        ExcluirSecretario.setText("Excluir");
        ExcluirSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirSecretarioActionPerformed(evt);
            }
        });

        NomeSecretario.setEnabled(false);

        jLabel5.setText("ID :");

        IDSecretario.setEnabled(false);

        NovoSecretario.setText("Novo");
        NovoSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoSecretarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroSecretario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPFSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(NomeSecretario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelarSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnviarSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NovoSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NovoSecretario)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(EnviarSecretario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditarSecretario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarSecretario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirSecretario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(IDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NomeSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPFSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NumeroSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setText("Secretario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoSecretarioActionPerformed
        flag = 1;
        NomeSecretario.setEnabled(true);
        CPFSecretario.setEnabled(true);
        NumeroSecretario.setEnabled(true);
       
        
        CancelarSecretario.setEnabled(true);
        EnviarSecretario.setEnabled(true);
        
        NovoSecretario.setEnabled(false);
        EditarSecretario.setEnabled(false);
        ExcluirSecretario.setEnabled(false);
        
        NomeSecretario.setText("");
        CPFSecretario.setText("");
        NumeroSecretario.setText("");
        
    }//GEN-LAST:event_NovoSecretarioActionPerformed

    private void EnviarSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarSecretarioActionPerformed
        if(NomeSecretario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar");
           NomeSecretario.requestFocus();
        }
        else if(CPFSecretario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o CPF para continuar");
           CPFSecretario.requestFocus();
        }
        else if(NumeroSecretario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha a TELEFONE para continuar");
           NumeroSecretario.requestFocus();
        }
        else if(flag == 1){        
            Mod.setNomeSecre(NomeSecretario.getText());
            Mod.setCpfSecre(CPFSecretario.getText());
            Mod.setTelSecre(NumeroSecretario.getText());
            Dao.Salvar(Mod);
        
        
           //LIMPA OS CAMPOS
           NomeSecretario.setText("");
           CPFSecretario.setText("");
           NumeroSecretario.setText("");
           IDSecretario.setText("");
           
           //BLOQUEIAS OS CAMPOS
           NomeSecretario.setEnabled(false);
           CPFSecretario.setEnabled(false);
           NumeroSecretario.setEnabled(false);
           IDSecretario.setEnabled(false);
           
               
           EnviarSecretario.setEnabled(false);
           NovoSecretario.setEnabled(true);
           EditarSecretario.setEnabled(false);
           CancelarSecretario.setEnabled(false);
        
          }else{
           Mod.setCodSecre(Integer.parseInt(IDSecretario.getText()));
           Mod.setNomeSecre(NomeSecretario.getText());
           Mod.setCpfSecre(CPFSecretario.getText());
           Mod.setTelSecre(NumeroSecretario.getText());
           Dao.AlterarSiim(Mod);
        
           //LIMPA OS CAMPOS
           NomeSecretario.setText("");
           CPFSecretario.setText("");
           NumeroSecretario.setText("");
           IDSecretario.setText("");
           
           //BLOQUEIAS OS CAMPOS
           NomeSecretario.setEnabled(false);
           CPFSecretario.setEnabled(false);
           NumeroSecretario.setEnabled(false);
           IDSecretario.setEnabled(false);
           
               
           EnviarSecretario.setEnabled(false);
           NovoSecretario.setEnabled(true);
           EditarSecretario.setEnabled(false);
           CancelarSecretario.setEnabled(false);
        
           }
        PreencherTabela("select * from secretario order by Nomesecre");//CHAMA A TABELA LOGO AO ABRIR
    }//GEN-LAST:event_EnviarSecretarioActionPerformed

    private void EditarSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarSecretarioActionPerformed
        flag = 2;
        NomeSecretario.setEnabled(true);
        CPFSecretario.setEnabled(true);
        NumeroSecretario.setEnabled(true);
       
        
        CancelarSecretario.setEnabled(true);
        EnviarSecretario.setEnabled(true);
        
        NovoSecretario.setEnabled(false);
        EditarSecretario.setEnabled(false);
        ExcluirSecretario.setEnabled(false);
        
        PreencherTabela("select * from secretario order by Nomesecre");//CHAMA A TABELA LOGO AO ABRIR
      
        
    }//GEN-LAST:event_EditarSecretarioActionPerformed

    private void CancelarSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarSecretarioActionPerformed
        NomeSecretario.setEnabled(!true);
        CPFSecretario.setEnabled(!true);
        NumeroSecretario.setEnabled(!true);      
        CancelarSecretario.setEnabled(!true);
        EnviarSecretario.setEnabled(!true);        
        NovoSecretario.setEnabled(!false);
        EditarSecretario.setEnabled(false);
        ExcluirSecretario.setEnabled(false);        
        NomeSecretario.setText("");
        CPFSecretario.setText("");
        NumeroSecretario.setText("");
        
    }//GEN-LAST:event_CancelarSecretarioActionPerformed

    private void ExcluirSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirSecretarioActionPerformed
        int Resposta = 0;
        Resposta =  JOptionPane.showConfirmDialog(rootPane,"Deseja excluir ?");
        if(Resposta == JOptionPane.YES_OPTION){
            Mod.setCodSecre(Integer.parseInt(IDSecretario.getText()));
            Dao.Excluir(Mod);
        }
        NomeSecretario.setText("");
        CPFSecretario.setText("");
        NumeroSecretario.setText("");
        IDSecretario.setText("");
        
        //BLOQUEIAS OS CAMPOS
        NomeSecretario.setEnabled(!true);
        CPFSecretario.setEnabled(!true);
        NumeroSecretario.setEnabled(!true);      
        CancelarSecretario.setEnabled(!true);
        EnviarSecretario.setEnabled(!true);        
        NovoSecretario.setEnabled(!false);
        EditarSecretario.setEnabled(false);
        ExcluirSecretario.setEnabled(false); 
        
        PreencherTabela("select * from secretario order by Nomesecre");//CHAMA A TABELA LOGO AO ABRIR
    }//GEN-LAST:event_ExcluirSecretarioActionPerformed

    private void TelaSecretarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaSecretarioMouseClicked
        String NomeSeecre=""+TelaSecretario.getValueAt(TelaSecretario.getSelectedRow(),1);
        Conex.Conexao();
        Conex.ExecultaSQL("select * from secretario where Nomesecre ='"+NomeSeecre+"'");
        try {
            Conex.Rs.first();
            IDSecretario.setText(String.valueOf(Conex.Rs.getInt("Coddensecre")));
            NomeSecretario.setText(Conex.Rs.getString("Nomesecre"));
            CPFSecretario.setText(Conex.Rs.getString("CPFsecre"));
            NumeroSecretario.setText(Conex.Rs.getString("Telsecre"));
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no Mouse USUARIO--\n\n"+ex);
        }
        Conex.Desconecta();
        
        
        NovoSecretario.setEnabled(false);
        EditarSecretario.setEnabled(true);
        ExcluirSecretario.setEnabled(true);
        CancelarSecretario.setEnabled(true);
        EnviarSecretario.setEnabled(false);
    }//GEN-LAST:event_TelaSecretarioMouseClicked
  
    
    public void PreencherTabela(String Sql){
        ArrayList Dados = new ArrayList();
        String [] Colunas = new String[]{"ID","NOME","CPF","TELEFONE"};
        Conex.Conexao();
        Conex.ExecultaSQL(Sql);
        
        try{
            Conex.Rs.first();
            do{
                Dados.add(new Object[]{Conex.Rs.getInt("Coddensecre"),Conex.Rs.getString("Nomesecre"),Conex.Rs.getString("CPFsecre"),Conex.Rs.getString("Telsecre")});//LINHA
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            if(flag > 0){
                JOptionPane.showMessageDialog(rootPane,"Busque novo SECRETARIO para preencher tabela \n\n"+ex);
            }
        }
        ModeloTabela Modelo = new ModeloTabela(Dados,Colunas);
        
        TelaSecretario.setModel(Modelo);
        TelaSecretario.getColumnModel().getColumn(0).setPreferredWidth(50);//TAMANHO E LARGURA COLUNA
        TelaSecretario.getColumnModel().getColumn(0).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TelaSecretario.getColumnModel().getColumn(1).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TelaSecretario.getColumnModel().getColumn(1).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TelaSecretario.getColumnModel().getColumn(2).setPreferredWidth(150);//TAMANHO E LARGURA COLUNA
        TelaSecretario.getColumnModel().getColumn(2).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TelaSecretario.getColumnModel().getColumn(3).setPreferredWidth(150);//TAMANHO E LARGURA COLUNA
        TelaSecretario.getColumnModel().getColumn(3).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
                
        TelaSecretario.getTableHeader().setReorderingAllowed(false);//NAO REORDENA CABECALHO
        TelaSecretario.setAutoResizeMode(TelaSecretario.AUTO_RESIZE_OFF);//NAO REDIME TABELA
        TelaSecretario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SO SELECIONA UM DADO POR VEZ
        
        Conex.Desconecta();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSecretario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CPFSecretario;
    private javax.swing.JButton CancelarSecretario;
    private javax.swing.JButton EditarSecretario;
    private javax.swing.JButton EnviarSecretario;
    private javax.swing.JButton ExcluirSecretario;
    private javax.swing.JTextField IDSecretario;
    private javax.swing.JTextField NomeSecretario;
    private javax.swing.JButton NovoSecretario;
    private javax.swing.JFormattedTextField NumeroSecretario;
    private javax.swing.JTable TelaSecretario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
