/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloBeans.BeansAgenda;
import ModeloBeans.ModeloTabela;
import ModeloConeciton.ConexaoBanco;
import ModeloDao.DaoAgenda;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Victor
 */
public class TelaAgenda extends javax.swing.JFrame {
    
    ConexaoBanco Conex = new ConexaoBanco();
    BeansAgenda agenda = new BeansAgenda();
        /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        PreencherTabelaPaciente("select * from paciente order by Nomepaci");//CHAMA A TABELA LOGO AO ABRIR
        PreencherDentistas();
        
    }
    
    public void PreencherDentistas (){
        
        Conex.Conexao();
        Conex.ExecultaSQL("select * from dent order by Nomedent");
        
        try{
            Conex.Rs.first();
            DentistasAgenda.removeAllItems();
            do{
               DentistasAgenda.addItem(Conex.Rs.getString("Nomedent"));
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            
               JOptionPane.showMessageDialog(rootPane,"Erro ao preencher MEDICOS"+ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Procedimento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HorarioAgenda = new javax.swing.JComboBox<>();
        ProcedimentoAgenda = new javax.swing.JComboBox<>();
        PacienteAgendaEScri = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPacientes = new javax.swing.JTable();
        EnviarAgenda = new javax.swing.JButton();
        CancelarAgenda = new javax.swing.JButton();
        DataAgenda = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        DentistasAgenda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Paciente :");

        jLabel3.setText("Dentista :");

        Procedimento.setText("Procedimento :");

        jLabel4.setText("Data :");

        jLabel5.setText("Horario :");

        HorarioAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "14:00", "15:00", "16:00", "17:00", " " }));

        ProcedimentoAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta", "Extracao", "Lente de Contado", "Limpeza", "Restauracao", "Cirurgia", " " }));

        PacienteAgendaEScri.setEnabled(false);

        TabelaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPacientes);

        EnviarAgenda.setText("Enviar");
        EnviarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarAgendaActionPerformed(evt);
            }
        });

        CancelarAgenda.setText("Cancelar");

        jLabel7.setText("Pacientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PacienteAgendaEScri, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(DentistasAgenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Procedimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProcedimentoAgenda, 0, 158, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HorarioAgenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DataAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(EnviarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CancelarAgenda)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(297, 297, 297))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PacienteAgendaEScri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DentistasAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Procedimento)
                    .addComponent(ProcedimentoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(DataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(HorarioAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarAgenda)
                    .addComponent(CancelarAgenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Agenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1021, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPacientesMouseClicked
        String NomePAACI =""+TabelaPacientes.getValueAt(TabelaPacientes.getSelectedRow(),1);
        Conex.Conexao();
        Conex.ExecultaSQL("select * from paciente where Nomepaci ='"+NomePAACI+"'");
        try {
            Conex.Rs.first();
            PacienteAgendaEScri.setText(Conex.Rs.getString("Nomepaci"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no Mouse-AGENDA PACIENTE\n\n"+ex);
        }
        Conex.Desconecta();
        CancelarAgenda.setEnabled(true);
        EnviarAgenda.setEnabled(true);
        
    }//GEN-LAST:event_TabelaPacientesMouseClicked

    private void EnviarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarAgendaActionPerformed
        agenda.setNomePaciAge(PacienteAgendaEScri.getText());
        
        agenda.setProcedimentoAge((String)ProcedimentoAgenda.getSelectedItem());
        agenda.setHorarioAge((String)HorarioAgenda.getSelectedItem());
        agenda.setDataAge(DataAgenda.getDate());
        agenda.setStatusAge("Aberto");
        DaoAgenda Dao = new DaoAgenda();
        Dao.Salvar(agenda);
        
        PreencherTabelaPaciente("select * from paciente order by Nomepaci");//CHAMA A TABELA LOGO AO ABRIR
        
        
        PacienteAgendaEScri.setText("");
        
        DataAgenda.setDateFormatString("");
    }//GEN-LAST:event_EnviarAgendaActionPerformed
    
    public void PreencherTabelaPaciente(String Sql){
        ArrayList Dados = new ArrayList();
        String [] Colunas = new String[]{"CODIGO","NOME","TELEFONE","PROCEDIMENTO"};
        Conex.Conexao();
        Conex.ExecultaSQL(Sql);
        
        try{
            Conex.Rs.first();
            do{
                Dados.add(new Object[]{Conex.Rs.getInt("Coddenpaci"),Conex.Rs.getString("Nomepaci"),Conex.Rs.getString("Telpaci"),Conex.Rs.getString("Procepaci")});//LINHA
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            
               JOptionPane.showMessageDialog(rootPane,"Busque novo PACIENTE para preencher tabela"+ex);
            
            
        }
        ModeloTabela Modelo = new ModeloTabela(Dados,Colunas);
        
        TabelaPacientes.setModel(Modelo);
        TabelaPacientes.getColumnModel().getColumn(0).setPreferredWidth(50);//TAMANHO E LARGURA COLUNA
        TabelaPacientes.getColumnModel().getColumn(0).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaPacientes.getColumnModel().getColumn(1).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaPacientes.getColumnModel().getColumn(1).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaPacientes.getColumnModel().getColumn(2).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaPacientes.getColumnModel().getColumn(2).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaPacientes.getColumnModel().getColumn(3).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaPacientes.getColumnModel().getColumn(3).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
                
        
        TabelaPacientes.getTableHeader().setReorderingAllowed(false);//NAO REORDENA CABECALHO
        TabelaPacientes.setAutoResizeMode(TabelaPacientes.AUTO_RESIZE_OFF);//NAO REDIME TABELA
        TabelaPacientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SO SELECIONA UM DADO POR VEZ
        
        Conex.Desconecta();
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarAgenda;
    private com.toedter.calendar.JDateChooser DataAgenda;
    private javax.swing.JComboBox<String> DentistasAgenda;
    private javax.swing.JButton EnviarAgenda;
    private javax.swing.JComboBox<String> HorarioAgenda;
    private javax.swing.JTextField PacienteAgendaEScri;
    private javax.swing.JLabel Procedimento;
    private javax.swing.JComboBox<String> ProcedimentoAgenda;
    private javax.swing.JTable TabelaPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
