/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloConeciton.ConexaoBanco;
import ModeloDao.DaoDent;
import ModeloBeans.BeansDent;
import ModeloBeans.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Victor
 */
public class TelaDentista extends javax.swing.JFrame {

    BeansDent Mod = new BeansDent();
    DaoDent Cont = new DaoDent();
    ConexaoBanco Conex = new ConexaoBanco();
    
    int flag = 0;
    
    public TelaDentista() {
        initComponents();
        
        PreencherTabela("select * from dent order by Nomedent");//CHAMA A TABELA LOGO AO ABRIR
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeTelaMedicos = new javax.swing.JLabel();
        RegistroTelaMedicos = new javax.swing.JLabel();
        TelefoneTelaMedicos = new javax.swing.JLabel();
        CPFTelaMedicos = new javax.swing.JLabel();
        AreaTelaMedicos = new javax.swing.JLabel();
        DigitarCPFTelaMedicos = new javax.swing.JTextField();
        DigitarTelefoneTelaMedicos = new javax.swing.JTextField();
        DigitarRegistroTelaMedicos = new javax.swing.JTextField();
        DigitarNomeTelaMedicos = new javax.swing.JTextField();
        EscolherAreaTelaMedicos = new javax.swing.JComboBox<>();
        BotaorNovoMedicoTelaMedicos = new javax.swing.JButton();
        BotaorEnviarTelaMedicos = new javax.swing.JButton();
        BotaorEditarTelaMedicos = new javax.swing.JButton();
        BotaorExcluirTelaMedicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaTelaMedicos = new javax.swing.JTable();
        BotaorLimparTelaMedicos = new javax.swing.JButton();
        IDTelaMedicos = new javax.swing.JLabel();
        DigitarIDTelaMedicos = new javax.swing.JTextField();
        MedicasTelaMedicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        NomeTelaMedicos.setText("Nome :");
        jPanel1.add(NomeTelaMedicos);
        NomeTelaMedicos.setBounds(50, 30, 42, 16);

        RegistroTelaMedicos.setText("Registro :");
        jPanel1.add(RegistroTelaMedicos);
        RegistroTelaMedicos.setBounds(50, 50, 60, 16);

        TelefoneTelaMedicos.setText("Telefone :");
        jPanel1.add(TelefoneTelaMedicos);
        TelefoneTelaMedicos.setBounds(50, 110, 60, 16);

        CPFTelaMedicos.setText("CPF :");
        jPanel1.add(CPFTelaMedicos);
        CPFTelaMedicos.setBounds(50, 80, 40, 16);

        AreaTelaMedicos.setText("Area :");
        jPanel1.add(AreaTelaMedicos);
        AreaTelaMedicos.setBounds(50, 140, 36, 20);

        DigitarCPFTelaMedicos.setEnabled(false);
        DigitarCPFTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarCPFTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(DigitarCPFTelaMedicos);
        DigitarCPFTelaMedicos.setBounds(120, 80, 290, 22);

        DigitarTelefoneTelaMedicos.setEnabled(false);
        DigitarTelefoneTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarTelefoneTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(DigitarTelefoneTelaMedicos);
        DigitarTelefoneTelaMedicos.setBounds(120, 110, 290, 22);

        DigitarRegistroTelaMedicos.setEnabled(false);
        DigitarRegistroTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarRegistroTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(DigitarRegistroTelaMedicos);
        DigitarRegistroTelaMedicos.setBounds(120, 50, 290, 22);

        DigitarNomeTelaMedicos.setEnabled(false);
        DigitarNomeTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarNomeTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(DigitarNomeTelaMedicos);
        DigitarNomeTelaMedicos.setBounds(120, 20, 290, 22);

        EscolherAreaTelaMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta", "Extracao", "Lente de Contado", "Limpeza", "Restauracao", "Cirurgia", " " }));
        EscolherAreaTelaMedicos.setEnabled(false);
        jPanel1.add(EscolherAreaTelaMedicos);
        EscolherAreaTelaMedicos.setBounds(120, 140, 290, 22);

        BotaorNovoMedicoTelaMedicos.setText("Novo Medico");
        BotaorNovoMedicoTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaorNovoMedicoTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(BotaorNovoMedicoTelaMedicos);
        BotaorNovoMedicoTelaMedicos.setBounds(570, 30, 140, 25);

        BotaorEnviarTelaMedicos.setText("Enviar");
        BotaorEnviarTelaMedicos.setEnabled(false);
        BotaorEnviarTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaorEnviarTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(BotaorEnviarTelaMedicos);
        BotaorEnviarTelaMedicos.setBounds(120, 180, 140, 25);

        BotaorEditarTelaMedicos.setText("Editar");
        BotaorEditarTelaMedicos.setEnabled(false);
        BotaorEditarTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaorEditarTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(BotaorEditarTelaMedicos);
        BotaorEditarTelaMedicos.setBounds(569, 70, 140, 25);

        BotaorExcluirTelaMedicos.setText("Excluir");
        BotaorExcluirTelaMedicos.setEnabled(false);
        BotaorExcluirTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaorExcluirTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(BotaorExcluirTelaMedicos);
        BotaorExcluirTelaMedicos.setBounds(569, 110, 140, 25);

        TabelaTelaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaTelaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTelaMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaTelaMedicos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(72, 260, 840, 160);

        BotaorLimparTelaMedicos.setText("Limpar");
        BotaorLimparTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaorLimparTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(BotaorLimparTelaMedicos);
        BotaorLimparTelaMedicos.setBounds(270, 180, 140, 25);

        IDTelaMedicos.setText("ID :");
        jPanel1.add(IDTelaMedicos);
        IDTelaMedicos.setBounds(420, 20, 21, 16);

        DigitarIDTelaMedicos.setEnabled(false);
        DigitarIDTelaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarIDTelaMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(DigitarIDTelaMedicos);
        DigitarIDTelaMedicos.setBounds(450, 20, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 40, 950, 440);

        MedicasTelaMedicos.setText("Medicos");
        getContentPane().add(MedicasTelaMedicos);
        MedicasTelaMedicos.setBounds(430, 10, 50, 20);

        setSize(new java.awt.Dimension(968, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DigitarCPFTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarCPFTelaMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarCPFTelaMedicosActionPerformed

    private void DigitarRegistroTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarRegistroTelaMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarRegistroTelaMedicosActionPerformed

    private void DigitarTelefoneTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarTelefoneTelaMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarTelefoneTelaMedicosActionPerformed

    private void BotaorEnviarTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaorEnviarTelaMedicosActionPerformed
        // TODO add your handling code here:
        
        if(DigitarNomeTelaMedicos.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar");
           DigitarNomeTelaMedicos.requestFocus();
        }
        else if(DigitarRegistroTelaMedicos.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o REGISTRO para continuar");
           DigitarRegistroTelaMedicos.requestFocus();
        }
        else if(DigitarCPFTelaMedicos.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o CPF para continuar");
           DigitarCPFTelaMedicos.requestFocus();
        }
        else if(DigitarTelefoneTelaMedicos.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o TELEFONE para continuar");
           DigitarTelefoneTelaMedicos.requestFocus();
        }else
        
        if(flag == 1){
        Mod.setNomeDent(DigitarNomeTelaMedicos.getText());
        Mod.setAreaDent((String)EscolherAreaTelaMedicos.getSelectedItem());
        Mod.setRegDent(DigitarRegistroTelaMedicos.getText());
        Mod.setCpfDent(DigitarCPFTelaMedicos.getText());
        Mod.setTelDent(DigitarTelefoneTelaMedicos.getText());
        Cont.Salvar(Mod);
        
        
        //LIMPA OS CAMPOS
        DigitarNomeTelaMedicos.setText("");
        DigitarRegistroTelaMedicos.setText("");
        DigitarCPFTelaMedicos.setText("");
        DigitarTelefoneTelaMedicos.setText("");
        
        //BLOQUEIAS OS CAMPOS
        DigitarNomeTelaMedicos.setEnabled(false);
        DigitarRegistroTelaMedicos.setEnabled(false);
        DigitarCPFTelaMedicos.setEnabled(false);
        DigitarTelefoneTelaMedicos.setEnabled(false);
        EscolherAreaTelaMedicos.setEnabled(false);       
        BotaorEnviarTelaMedicos.setEnabled(false);
        
        }
        else{
            Mod.setCodDent((Integer.parseInt(DigitarIDTelaMedicos.getText())));
            Mod.setNomeDent(DigitarNomeTelaMedicos.getText());
            Mod.setRegDent(DigitarRegistroTelaMedicos.getText());
            Mod.setCpfDent(DigitarCPFTelaMedicos.getText());
            Mod.setTelDent(DigitarTelefoneTelaMedicos.getText());
            Mod.setAreaDent((String)EscolherAreaTelaMedicos.getSelectedItem());
            
            Cont.Editar(Mod);
            
            DigitarNomeTelaMedicos.setEnabled(true);
            DigitarRegistroTelaMedicos.setEnabled(true);
            DigitarCPFTelaMedicos.setEnabled(true);
            DigitarTelefoneTelaMedicos.setEnabled(true);
            EscolherAreaTelaMedicos.setEnabled(true);       
            BotaorEnviarTelaMedicos.setEnabled(true);
            BotaorNovoMedicoTelaMedicos.setEnabled(true);
            
            
            DigitarNomeTelaMedicos.setText("");
            DigitarRegistroTelaMedicos.setText("");
            DigitarCPFTelaMedicos.setText("");
            DigitarTelefoneTelaMedicos.setText("");
       
            
            
        }
        PreencherTabela("select * from dent order by Nomedent");//CHAMA A TABELA LOGO AO ABRIR
    }//GEN-LAST:event_BotaorEnviarTelaMedicosActionPerformed

    private void DigitarNomeTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarNomeTelaMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarNomeTelaMedicosActionPerformed

    private void BotaorNovoMedicoTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaorNovoMedicoTelaMedicosActionPerformed
        flag = 1;
        DigitarNomeTelaMedicos.setEnabled(true);
        DigitarRegistroTelaMedicos.setEnabled(true);
        DigitarCPFTelaMedicos.setEnabled(true);
        DigitarTelefoneTelaMedicos.setEnabled(true);
        EscolherAreaTelaMedicos.setEnabled(true);
        BotaorEnviarTelaMedicos.setEnabled(true);
        BotaorLimparTelaMedicos.setEnabled(true);
        
        DigitarNomeTelaMedicos.setText("");
        DigitarRegistroTelaMedicos.setText("");
        DigitarCPFTelaMedicos.setText("");
        DigitarTelefoneTelaMedicos.setText("");
        DigitarIDTelaMedicos.setText("");
        BotaorLimparTelaMedicos.setEnabled(false);
        BotaorEditarTelaMedicos.setEnabled(false);
        BotaorExcluirTelaMedicos.setEnabled(false);
        
        
        
    }//GEN-LAST:event_BotaorNovoMedicoTelaMedicosActionPerformed

    private void BotaorEditarTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaorEditarTelaMedicosActionPerformed
        flag = 2;
        DigitarNomeTelaMedicos.setEnabled(true);
        DigitarRegistroTelaMedicos.setEnabled(true);
        DigitarCPFTelaMedicos.setEnabled(true);
        DigitarTelefoneTelaMedicos.setEnabled(true);
        EscolherAreaTelaMedicos.setEnabled(true);
        BotaorEnviarTelaMedicos.setEnabled(true);
        BotaorLimparTelaMedicos.setEnabled(true);
        BotaorNovoMedicoTelaMedicos.setEnabled(false);
        BotaorExcluirTelaMedicos.setEnabled(false);
        PreencherTabela("select * from dent order by Nomedent");//CHAMA A TABELA LOGO AO ABRIR
        
    }//GEN-LAST:event_BotaorEditarTelaMedicosActionPerformed

    private void BotaorLimparTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaorLimparTelaMedicosActionPerformed
        DigitarNomeTelaMedicos.setEnabled(!true);
        DigitarRegistroTelaMedicos.setEnabled(!true);
        DigitarCPFTelaMedicos.setEnabled(!true);
        DigitarTelefoneTelaMedicos.setEnabled(!true);
        EscolherAreaTelaMedicos.setEnabled(!true);
        BotaorEnviarTelaMedicos.setEnabled(!true);
        BotaorLimparTelaMedicos.setEnabled(!true);
        BotaorNovoMedicoTelaMedicos.setEnabled(true);
        BotaorEditarTelaMedicos.setEnabled(false);
        BotaorExcluirTelaMedicos.setEnabled(false);
        BotaorEnviarTelaMedicos.setEnabled(false);
       
        
        DigitarNomeTelaMedicos.setText("");
        DigitarRegistroTelaMedicos.setText("");
        DigitarCPFTelaMedicos.setText("");
        DigitarTelefoneTelaMedicos.setText("");
        DigitarIDTelaMedicos.setText("");
       
    }//GEN-LAST:event_BotaorLimparTelaMedicosActionPerformed

    private void DigitarIDTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarIDTelaMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarIDTelaMedicosActionPerformed

    private void BotaorExcluirTelaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaorExcluirTelaMedicosActionPerformed
        int Resposta = 0;
        Resposta =  JOptionPane.showConfirmDialog(rootPane,"Deseja excluir ?");
        if(Resposta == JOptionPane.YES_OPTION){
            Mod.setCodDent(Integer.parseInt(DigitarIDTelaMedicos.getText()));
            Cont.Excluir(Mod);
            
            DigitarNomeTelaMedicos.setEnabled(false);
            DigitarRegistroTelaMedicos.setEnabled(false);
            DigitarCPFTelaMedicos.setEnabled(false);
            DigitarTelefoneTelaMedicos.setEnabled(false);
            EscolherAreaTelaMedicos.setEnabled(false);       
            BotaorEnviarTelaMedicos.setEnabled(false);
            BotaorNovoMedicoTelaMedicos.setEnabled(true);
            
            
            BotaorEditarTelaMedicos.setEnabled(false);
            BotaorExcluirTelaMedicos.setEnabled(false);
            
            DigitarNomeTelaMedicos.setText("");
            DigitarRegistroTelaMedicos.setText("");
            DigitarCPFTelaMedicos.setText("");
            DigitarTelefoneTelaMedicos.setText("");
        }
        
        
      PreencherTabela("select * from dent order by Nomedent");//CHAMA A TABELA LOGO AO ABRIR  
    }//GEN-LAST:event_BotaorExcluirTelaMedicosActionPerformed

    private void TabelaTelaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTelaMedicosMouseClicked

        String Nomedent =""+TabelaTelaMedicos.getValueAt(TabelaTelaMedicos.getSelectedRow(),1);
        Conex.Conexao();
        Conex.ExecultaSQL("select * from dent where Nomedent ='"+Nomedent+"'");
        try {
            Conex.Rs.first();
            DigitarIDTelaMedicos.setText(String.valueOf(Conex.Rs.getInt("Codden")));
            DigitarNomeTelaMedicos.setText(Conex.Rs.getString("Nomedent"));
            DigitarRegistroTelaMedicos.setText(Conex.Rs.getString("Registro"));
            DigitarCPFTelaMedicos.setText(Conex.Rs.getString("Cpfden"));
            DigitarTelefoneTelaMedicos.setText(Conex.Rs.getString("Telden"));
            EscolherAreaTelaMedicos.setSelectedItem(Conex.Rs.getString("Areaden"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no Mouse\n\n"+ex);
        }
        Conex.Desconecta();
        BotaorExcluirTelaMedicos.setEnabled(true);
        BotaorEditarTelaMedicos.setEnabled(true);

    }//GEN-LAST:event_TabelaTelaMedicosMouseClicked

    public void PreencherTabela(String Sql){
        ArrayList Dados = new ArrayList();
        String [] Colunas = new String[]{"CODIGO","NOME","REGISTRO","CPF","TELEFONE","AREA"};
        Conex.Conexao();
        Conex.ExecultaSQL(Sql);
        
        try{
            Conex.Rs.first();
            do{
                Dados.add(new Object[]{Conex.Rs.getInt("Codden"),Conex.Rs.getString("Nomedent"),Conex.Rs.getString("Registro"),Conex.Rs.getString("Cpfden"),Conex.Rs.getString("Telden"),Conex.Rs.getString("Areaden")});//LINHA
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            if(flag > 0){
                JOptionPane.showMessageDialog(rootPane,"Busque novo DENTISTA para preencher tabela"+ex);
            }
            
        }
        ModeloTabela Modelo = new ModeloTabela(Dados,Colunas);
        
        TabelaTelaMedicos.setModel(Modelo);
        TabelaTelaMedicos.getColumnModel().getColumn(0).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(0).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(1).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(1).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(2).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(2).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(3).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(3).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(4).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(4).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(5).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaTelaMedicos.getColumnModel().getColumn(5).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        
        TabelaTelaMedicos.getTableHeader().setReorderingAllowed(false);//NAO REORDENA CABECALHO
        TabelaTelaMedicos.setAutoResizeMode(TabelaTelaMedicos.AUTO_RESIZE_OFF);//NAO REDIME TABELA
        TabelaTelaMedicos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SO SELECIONA UM DADO POR VEZ
        
        Conex.Desconecta();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDentista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaTelaMedicos;
    private javax.swing.JButton BotaorEditarTelaMedicos;
    private javax.swing.JButton BotaorEnviarTelaMedicos;
    private javax.swing.JButton BotaorExcluirTelaMedicos;
    private javax.swing.JButton BotaorLimparTelaMedicos;
    private javax.swing.JButton BotaorNovoMedicoTelaMedicos;
    private javax.swing.JLabel CPFTelaMedicos;
    private javax.swing.JTextField DigitarCPFTelaMedicos;
    private javax.swing.JTextField DigitarIDTelaMedicos;
    private javax.swing.JTextField DigitarNomeTelaMedicos;
    private javax.swing.JTextField DigitarRegistroTelaMedicos;
    private javax.swing.JTextField DigitarTelefoneTelaMedicos;
    private javax.swing.JComboBox<String> EscolherAreaTelaMedicos;
    private javax.swing.JLabel IDTelaMedicos;
    private javax.swing.JLabel MedicasTelaMedicos;
    private javax.swing.JLabel NomeTelaMedicos;
    private javax.swing.JLabel RegistroTelaMedicos;
    private javax.swing.JTable TabelaTelaMedicos;
    private javax.swing.JLabel TelefoneTelaMedicos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
