/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloBeans.BeansUsuario;
import ModeloBeans.ModeloTabela;
import ModeloConeciton.ConexaoBanco;
import ModeloDao.DaoUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Victor
 */
public class TelaUsuario extends javax.swing.JFrame {

    BeansUsuario Mod = new BeansUsuario();
    DaoUsuario Dao = new DaoUsuario();
    ConexaoBanco Conex = new ConexaoBanco(); 
    int flag = 0;
    
   
    
    public TelaUsuario() {
        initComponents(); 
        PreencherTabela("select * from usuario order by Nomeusu");//CHAMA A TABELA LOGO AO ABRIR
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JTextField();
        LoginUsuario = new javax.swing.JTextField();
        SenhaUsuario = new javax.swing.JPasswordField();
        CSenhaUsuario = new javax.swing.JPasswordField();
        NovoUsuario = new javax.swing.JButton();
        EnviarUsuario = new javax.swing.JButton();
        EditarUsuario = new javax.swing.JButton();
        ExcluirUsuario = new javax.swing.JButton();
        CancelarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IDUsuario = new javax.swing.JTextField();
        TipoUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        UsiarioText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Nome.setText("Nome :");

        Login.setText("Login :");

        Senha.setText("Senha :");

        jLabel2.setText("Confirmar Senha :");

        NomeUsuario.setEnabled(false);
        NomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeUsuarioActionPerformed(evt);
            }
        });

        LoginUsuario.setEnabled(false);

        SenhaUsuario.setEnabled(false);

        CSenhaUsuario.setEnabled(false);

        NovoUsuario.setText("Novo");
        NovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoUsuarioActionPerformed(evt);
            }
        });

        EnviarUsuario.setText("Enviar");
        EnviarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarUsuarioActionPerformed(evt);
            }
        });

        EditarUsuario.setText("Editar");
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });

        ExcluirUsuario.setText("Excluir");
        ExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirUsuarioActionPerformed(evt);
            }
        });

        CancelarUsuario.setText("Cancelar");
        CancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarUsuarioActionPerformed(evt);
            }
        });

        TabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaUsuario);

        jLabel1.setText("ID :");

        IDUsuario.setEnabled(false);
        IDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDUsuarioActionPerformed(evt);
            }
        });

        TipoUsuario.setEditable(true);
        TipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Secretario", "Dentista", " " }));
        TipoUsuario.setEnabled(false);

        jLabel3.setText("Tipo :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Login)
                            .addGap(18, 18, 18)
                            .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Senha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CSenhaUsuario)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nome)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnviarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarUsuario)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha)
                    .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoUsuario)
                    .addComponent(EnviarUsuario)
                    .addComponent(EditarUsuario)
                    .addComponent(ExcluirUsuario)
                    .addComponent(CancelarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        UsiarioText.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(UsiarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UsiarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1066, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoUsuarioActionPerformed
        flag = 1;
        NomeUsuario.setEnabled(true);
        LoginUsuario.setEnabled(true);
        SenhaUsuario.setEnabled(true);
        CSenhaUsuario.setEnabled(true);
        TipoUsuario.setEnabled(true);
        
        CancelarUsuario.setEnabled(true);
        EnviarUsuario.setEnabled(true);
        
        NovoUsuario.setEnabled(false);
        
        EditarUsuario.setEnabled(false);
        ExcluirUsuario.setEnabled(false);
        
        NomeUsuario.setText("");
        LoginUsuario.setText("");
        SenhaUsuario.setText("");
        CSenhaUsuario.setText("");
        
        
        
    }//GEN-LAST:event_NovoUsuarioActionPerformed

    private void EnviarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarUsuarioActionPerformed
        if(NomeUsuario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar");
           NomeUsuario.requestFocus();
        }
        else if(LoginUsuario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o LOGIN para continuar");
           LoginUsuario.requestFocus();
        }
        else if(SenhaUsuario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha a SENHA para continuar");
           SenhaUsuario.requestFocus();
        }
        else if(CSenhaUsuario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o CONFIRMA SENHA para continuar");
           CSenhaUsuario.requestFocus();
        }else if(SenhaUsuario.getText().equals(CSenhaUsuario.getText())){
            if(flag == 1){        
            Mod.setNomeUsu(NomeUsuario.getText());
            Mod.setLoginUsu(LoginUsuario.getText());
            Mod.setSenhaUsu(SenhaUsuario.getText());
            Mod.setTipoUsu((String)TipoUsuario.getSelectedItem());
            Dao.Salvar(Mod);
        
        
           //LIMPA OS CAMPOS
           NomeUsuario.setText("");
           LoginUsuario.setText("");
           SenhaUsuario.setText("");
           CSenhaUsuario.setText("");
           IDUsuario.setText("");
           
           //BLOQUEIAS OS CAMPOS
           NomeUsuario.setEnabled(false);
           LoginUsuario.setEnabled(false);
           SenhaUsuario.setEnabled(false);
           CSenhaUsuario.setEnabled(false);
           TipoUsuario.setEnabled(false);       
           EnviarUsuario.setEnabled(false);
           NovoUsuario.setEnabled(true);
           EditarUsuario.setEnabled(false);
           CancelarUsuario.setEnabled(false);
        
          }else{
           Mod.setCoddenUsu(Integer.parseInt(IDUsuario.getText()));
           Mod.setNomeUsu(NomeUsuario.getText());
           Mod.setLoginUsu(LoginUsuario.getText());
           Mod.setSenhaUsu(SenhaUsuario.getText());
           Mod.setTipoUsu((String)TipoUsuario.getSelectedItem());
           Dao.Alteraroi(Mod);
        
           //LIMPA OS CAMPOS
           NomeUsuario.setText("");
           LoginUsuario.setText("");
           SenhaUsuario.setText("");
           CSenhaUsuario.setText("");
           IDUsuario.setText("");
        
           //BLOQUEIAS OS CAMPOS
           NomeUsuario.setEnabled(false);
           LoginUsuario.setEnabled(false);
           SenhaUsuario.setEnabled(false);
           CSenhaUsuario.setEnabled(false);
           TipoUsuario.setEnabled(false);       
           EnviarUsuario.setEnabled(false);
           NovoUsuario.setEnabled(true);
           EditarUsuario.setEnabled(false);
           CancelarUsuario.setEnabled(false);
        
           } 
        }else{JOptionPane.showMessageDialog(null, "SENHAS DEVEM SER IGUAIS");}
        PreencherTabela("select * from usuario order by Nomeusu");//CHAMA A TABELA LOGO AO ABRIR  
    }//GEN-LAST:event_EnviarUsuarioActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        flag = 2;
        NomeUsuario.setEnabled(true);
        LoginUsuario.setEnabled(true);
        SenhaUsuario.setEnabled(true);
        CSenhaUsuario.setEnabled(true);
        TipoUsuario.setEnabled(true);
        CancelarUsuario.setEnabled(true);
        EnviarUsuario.setEnabled(true);
        EditarUsuario.setEnabled(false);
        
        
        PreencherTabela("select * from usuario order by Nomeusu");//CHAMA A TABELA LOGO AO ABRIR
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void ExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirUsuarioActionPerformed
        int Resposta = 0;
        Resposta =  JOptionPane.showConfirmDialog(rootPane,"Deseja excluir ?");
        if(Resposta == JOptionPane.YES_OPTION){
            Mod.setCoddenUsu(Integer.parseInt(IDUsuario.getText()));
            Dao.Excluir(Mod);
        }
        NomeUsuario.setText("");
        LoginUsuario.setText("");
        SenhaUsuario.setText("");
        CSenhaUsuario.setText("");
        IDUsuario.setText("");
        
        //BLOQUEIAS OS CAMPOS
        NomeUsuario.setEnabled(false);
        LoginUsuario.setEnabled(false);
        SenhaUsuario.setEnabled(false);
        CSenhaUsuario.setEnabled(false);
        TipoUsuario.setEnabled(false);       
        EnviarUsuario.setEnabled(false);
        NovoUsuario.setEnabled(true);
        EditarUsuario.setEnabled(false);
        CancelarUsuario.setEnabled(false);
        ExcluirUsuario.setEnabled(false);
        
        PreencherTabela("select * from usuario order by Nomeusu");//CHAMA A TABELA LOGO AO ABRIR
    }//GEN-LAST:event_ExcluirUsuarioActionPerformed

    private void TabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseClicked

        String Nomedent =""+TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(),1);
        Conex.Conexao();
        Conex.ExecultaSQL("select * from usuario where Nomeusu ='"+Nomedent+"'");
        try {
            Conex.Rs.first();
            IDUsuario.setText(String.valueOf(Conex.Rs.getInt("Coddenusu")));
            NomeUsuario.setText(Conex.Rs.getString("Nomeusu"));
            LoginUsuario.setText(Conex.Rs.getString("Loginusu"));
            SenhaUsuario.setText(Conex.Rs.getString("Senhausu"));
            CSenhaUsuario.setText(Conex.Rs.getString("Senhausu"));
            TipoUsuario.setSelectedItem(Conex.Rs.getString("Tipousu"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no Mouse USUARIO--\n\n"+ex);
        }
        Conex.Desconecta();
        
        
        NovoUsuario.setEnabled(false);
        EditarUsuario.setEnabled(true);
        ExcluirUsuario.setEnabled(true);
        CancelarUsuario.setEnabled(true);
        EnviarUsuario.setEnabled(false);
        
                
    }//GEN-LAST:event_TabelaUsuarioMouseClicked

    private void CancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarUsuarioActionPerformed
        NomeUsuario.setEnabled(!true);
        LoginUsuario.setEnabled(!true);
        SenhaUsuario.setEnabled(!true);
        CSenhaUsuario.setEnabled(!true);
        TipoUsuario.setEnabled(!true);
        CancelarUsuario.setEnabled(!true);
        EnviarUsuario.setEnabled(!true);
        NovoUsuario.setEnabled(true);
        
        EditarUsuario.setEnabled(false);
        ExcluirUsuario.setEnabled(false);
       
        NomeUsuario.setText("");
        LoginUsuario.setText("");
        SenhaUsuario.setText("");
        CSenhaUsuario.setText("");
    }//GEN-LAST:event_CancelarUsuarioActionPerformed

    private void IDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDUsuarioActionPerformed

    private void NomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeUsuarioActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }
    
     public void PreencherTabela(String Sql){
        ArrayList Dados = new ArrayList();
        String [] Colunas = new String[]{"ID","NOME","LOGIN","SENHA","TIPO"};
        Conex.Conexao();
        Conex.ExecultaSQL(Sql);
        
        try{
            Conex.Rs.first();
            do{
                Dados.add(new Object[]{Conex.Rs.getInt("Coddenusu"),Conex.Rs.getString("Nomeusu"),Conex.Rs.getString("Loginusu"),Conex.Rs.getString("Senhausu"),Conex.Rs.getString("Tipousu")});//LINHA
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            if(flag > 0){
                JOptionPane.showMessageDialog(rootPane,"Busque novo usuario para preencher tabela \n\n"+ex);
            }
        }
        ModeloTabela Modelo = new ModeloTabela(Dados,Colunas);
        
        TabelaUsuario.setModel(Modelo);
        TabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);//TAMANHO E LARGURA COLUNA
        TabelaUsuario.getColumnModel().getColumn(0).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);//TAMANHO E LARGURA COLUNA
        TabelaUsuario.getColumnModel().getColumn(1).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaUsuario.getColumnModel().getColumn(2).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaUsuario.getColumnModel().getColumn(3).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaUsuario.getColumnModel().getColumn(4).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaUsuario.getColumnModel().getColumn(4).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        
        TabelaUsuario.getTableHeader().setReorderingAllowed(false);//NAO REORDENA CABECALHO
        TabelaUsuario.setAutoResizeMode(TabelaUsuario.AUTO_RESIZE_OFF);//NAO REDIME TABELA
        TabelaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SO SELECIONA UM DADO POR VEZ
        
        Conex.Desconecta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CSenhaUsuario;
    private javax.swing.JButton CancelarUsuario;
    private javax.swing.JButton EditarUsuario;
    private javax.swing.JButton EnviarUsuario;
    private javax.swing.JButton ExcluirUsuario;
    private javax.swing.JTextField IDUsuario;
    private javax.swing.JLabel Login;
    private javax.swing.JTextField LoginUsuario;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeUsuario;
    private javax.swing.JButton NovoUsuario;
    private javax.swing.JLabel Senha;
    private javax.swing.JPasswordField SenhaUsuario;
    private javax.swing.JTable TabelaUsuario;
    private javax.swing.JComboBox<String> TipoUsuario;
    private javax.swing.JLabel UsiarioText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
