/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloBeans.BeansAgenda;
import ModeloBeans.ModeloTabela;
import ModeloConeciton.ConexaoBanco;
import ModeloDao.DaoAgenda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Victor
 */
public class TelaAgendaDiaria extends javax.swing.JFrame {
    ConexaoBanco Conex = new ConexaoBanco();
    BeansAgenda Agenda = new BeansAgenda();
    BeansAgenda Agen = new BeansAgenda();
    DaoAgenda DaoAge = new DaoAgenda();
    
    String Status;
    String DHoje;
    /**
     * Creates new form TelaAgendaDiaria
     */
    public TelaAgendaDiaria() {
        initComponents();
        
        Calendar data = Calendar.getInstance();
        Date datta = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(datta); 
        
        
        DHoje = dateFormat.format(datta);
        Status = "Aberto";
        
        PreencherTabela("select * from agenda inner join paciente on PacienteCodage=Coddenpaci inner join dent on DentistaCodage=Codden where Dataage='"+DHoje+"' and Statusage='"+Status+"' order by Horarioage");
        
                
        
    }
    
    public void PreencherTabela(String Sql){
        ArrayList Dados = new ArrayList();
        String [] Colunas = new String[]{"ID","NOME PACIENTE","NOME DENTISTA","HORARIO","DATA","STATUS"};
        Conex.Conexao();
        Conex.ExecultaSQL(Sql);
        
        try{
            Conex.Rs.first();
            do{
                Dados.add(new Object[]{Conex.Rs.getInt("Coddenage"),
                    Conex.Rs.getString("Nomepaci"),
                    Conex.Rs.getString("Nomedent"),
                    Conex.Rs.getString("Horarioage"),
                    Conex.Rs.getString("Dataage"),
                    Conex.Rs.getString("Statusage")});//LINHA
                
            }while(Conex.Rs.next());//TEM DADOS VAI PERCORRER
        }catch(SQLException ex){
            
                JOptionPane.showMessageDialog(rootPane,"Sem atendimentos hoje");
            
        }
        ModeloTabela Modelo = new ModeloTabela(Dados,Colunas);
        
        TabelaAgendaDia.setModel(Modelo);
        TabelaAgendaDia.getColumnModel().getColumn(0).setPreferredWidth(50);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(0).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(1).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(1).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(2).setPreferredWidth(200);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(2).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(3).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(3).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(4).setPreferredWidth(100);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(4).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(5).setPreferredWidth(150);//TAMANHO E LARGURA COLUNA
        TabelaAgendaDia.getColumnModel().getColumn(5).setResizable(false);//NAO MUDAR O TAMANHO DA COLUNA
        
        TabelaAgendaDia.getTableHeader().setReorderingAllowed(false);//NAO REORDENA CABECALHO
        TabelaAgendaDia.setAutoResizeMode(TabelaAgendaDia.AUTO_RESIZE_OFF);//NAO REDIME TABELA
        TabelaAgendaDia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SO SELECIONA UM DADO POR VEZ
        
        Conex.Desconecta();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAgendaDia = new javax.swing.JTable();
        AtenderAgendaDiaria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaAgendaDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaAgendaDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAgendaDiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAgendaDia);

        AtenderAgendaDiaria.setText("Atender");
        AtenderAgendaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtenderAgendaDiariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtenderAgendaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AtenderAgendaDiaria)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setText("Agenda Diaria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        setSize(new java.awt.Dimension(976, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaAgendaDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAgendaDiaMouseClicked
      String AgendaDia =""+TabelaAgendaDia.getValueAt(TabelaAgendaDia.getSelectedRow(),0);
        Conex.Conexao();
        Conex.ExecultaSQL("select * from agenda where Coddenage ='"+AgendaDia+"'");
        try {
            Conex.Rs.first();
            Agen.setStatusAge("Atendido");
            Agen.setCoddenAge(Conex.Rs.getInt("Coddenage"));
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no Mouse\n\n"+ex);
        }
        Conex.Desconecta();        
    }//GEN-LAST:event_TabelaAgendaDiaMouseClicked

    private void AtenderAgendaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtenderAgendaDiariaActionPerformed
        DaoAge.Alterar(Agen);
        PreencherTabela("select * from agenda inner join paciente on PacienteCodage=Coddenpaci inner join dent on DentistaCodage=Codden where Dataage='"+DHoje+"' and Statusage='"+Status+"' order by Horarioage");
    }//GEN-LAST:event_AtenderAgendaDiariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendaDiaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtenderAgendaDiaria;
    private javax.swing.JTable TabelaAgendaDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
